{
        "name": "DJI Mini 4 Pro (DJI RC-N2)",
        "price": 3799900,
        "description": "El DJI Mini 4 Pro es un dron ultra ligero y avanzado, diseñado para capturar video 4K HDR y fotos aéreas de alta calidad con máxima estabilidad y seguridad. Su control RC-N2 ofrece una conexión más estable y baja latencia, ideal para vuelos precisos. La versión estándar incluye el dron, el control RC-N2, una batería inteligente, hélices de repuesto, cableado completo y protector de gimbal, listo para volar desde el primer momento.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2023/10/1695671537_IMG_2087266_500x.webp",
        "categoryId": 1,
        "stock": 10
    },

{
        "name": "DJI Mini 4 Pro (DJI RC2)",
        "price": 3999900,
        "description": "El DJI Mini 4 Pro es un dron compacto, ligero y muy potente, ideal para capturar videos 4K HDR y fotos aéreas de alta calidad con sensores avanzados para un vuelo más seguro. La versión con control RC 2 ofrece una señal más estable y mayor alcance gracias a O4, además de una experiencia de vuelo precisa e intuitiva. Incluye el dron, el control RC 2, una batería inteligente, hélices de repuesto, cables y protector de gimbal, listo para usar desde el primer vuelo.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2023/10/3prod_500x.webp",
        "categoryId": 1,
        "stock": 10
    },

{
        "name": "DJI Mini 4 Pro Fly More Combo (DJI RC2)",
        "price": 4499900,
        "description": "El DJI Mini 4 Pro Fly More Combo con control RC 2 es un paquete completo pensado para aprovechar al máximo cada vuelo. Ofrece video 4K HDR, sensores avanzados para mayor seguridad y un diseño ultraligero fácil de llevar a cualquier lugar. El control RC 2 garantiza una conexión más estable y de largo alcance gracias a O4. El combo incluye el dron, el control RC 2, tres baterías inteligentes, hub de carga, hélices de repuesto, estuche de transporte y accesorios adicionales, ideal para sesiones más largas y sin interrupciones.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2025/01/dji-mini-4-pro-drone-fly-more-combo-plus-with-rc-2-controller-front.webp",
        "categoryId": 1,
        "stock": 10
    },

{
        "name": "DJI Mini 5 Pro Fly More Combo (DJI RC-N3)",
        "price": 4999900,
        "description": "El DJI Mini 5 Pro Fly More Combo con control RC-N3 es un dron ultraligero y potente diseñado para capturar videos en alta definición y fotografías aéreas con máxima estabilidad. Incluye sensores avanzados para un vuelo seguro, y su control RC-N2 brinda una señal confiable y de largo alcance, ideal para vuelos precisos. En el combo encontrarás el dron, el control RC-N2, tres baterías inteligentes, un hub de carga, hélices de repuesto y un estuche de transporte, para que puedas volar más tiempo y con tranquilidad.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2025/09/DJI_Mini_5_Pro_Fly_More_Combo_DJI_RC-N3_2-1024x683.webp",
        "categoryId": 1,
        "stock": 10
    },

{
        "name": "DJI Mini 5 Pro Fly More Combo (DJI RC2)",
        "price": 4999900,
        "description": "El DJI Mini 5 Pro Fly More Combo con control RC 2 ofrece una experiencia de vuelo completa y confiable, ideal para quienes buscan calidad de imagen y mayor autonomía. Su sistema de transmisión O4 permite una conexión estable y un control preciso a larga distancia, mientras su cámara renovada captura video detallado y fotografías nítidas incluso en condiciones exigentes. El combo incluye tres baterías, hub de carga, hélices de repuesto, estuche de transporte y todos los accesorios necesarios para disfrutar sesiones de vuelo prolongadas desde el primer día.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2025/09/DJI-Mini-5-Pro-Fly-More-Combo-DJI-RC-2-2-scaled.jpg",
        "categoryId": 1,
        "stock": 10
    },

{
        "name": "DJI Osmo Pocket 3 Creator Combo",
        "price": 2999900,
        "description": "La DJI Osmo Pocket 3 Creator Combo es la herramienta perfecta para creadores que quieren calidad profesional en un dispositivo compacto. Con su sensor de alta resolución, estabilización avanzada y grabación en 4K o más, permite capturar video fluido y nítido desde cualquier ángulo. El combo incluye la Osmo Pocket 3, micrófono externo, empuñadura con controles adicionales, trípode pequeño, filtro ND y accesorios para potenciar tus producciones. Ideal para vlogging, viajes, cine independiente y contenido creativo en movimiento.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2024/03/IMG_8202.jpeg",
        "categoryId": 3,
        "stock": 10
    },

{
        "name": "DJI Osmo Nano (128 GB)",
        "price": 1599900,
        "description": "La DJI Osmo Nano con 128 GB es una cámara de vlogging ultracompacta que lleva calidad avanzada a la palma de tu mano. Gracias a su diseño minimalista y muy ligera, puedes grabar video 4K con estabilización electrónica para tomas suaves sin necesidad de trípodes voluminosos. Su almacenamiento interno de 128 GB te da espacio amplio para grabar largos periodos sin preocuparte por tarjetas externas. Ideal para creadores móviles, viajeros y cualquiera que quiera capturar momentos en alta resolución sin sacrificar portabilidad.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2025/10/Osmo-Nano-in-the-box-2-scaled.jpg",
        "categoryId": 3,
        "stock": 10
    },

{
        "name": "DJI Osmo 360 Adventure Combo",
        "price": 2899900,
        "description": "La DJI Osmo 360 Adventure Combo te permite capturar el mundo en 360° con resolución 8K, fotos de 120 MP y estabilización avanzada. Compacta, resistente y lista para cualquier aventura, ofrece color de 10 bits, grabación fluida y accesorios magnéticos para máxima creatividad en movimiento.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2025/08/WhatsApp-Image-2025-08-21-at-4.17.15-PM.jpeg",
        "categoryId": 3,
        "stock": 10
    },

{
        "name": "DJI Osmo 360 Standard Combo",
        "price": 2299900,
        "description": "La DJI Osmo 360 Adventure Combo te permite capturar el mundo en 360° con resolución 8K, fotos de 120 MP y estabilización avanzada. Compacta, resistente y lista para cualquier aventura, ofrece color de 10 bits, grabación fluida y accesorios magnéticos para máxima creatividad en movimiento.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2025/08/WhatsApp-Image-2025-08-21-at-4.14.48-PM1.jpeg",
        "categoryId": 3,
        "stock": 10
    },

{
        "name": "DJI Osmo Action 5 pro Adventure Combo",
        "price": 2399900,
        "description": "La DJI Osmo Action 5 Pro Adventure Combo es la cámara ideal para quienes buscan calidad profesional en cualquier aventura. Su sensor mejorado, estabilización avanzada y grabación en 4K/8K permiten capturar imágenes nítidas y fluidas incluso en movimiento. El combo incluye la Action 5 Pro, baterías adicionales, empuñadura resistente, soportes adhesivos, carcasa protectora y accesorios esenciales para aventuras extremas. Perfecta para deportes, viajes, vlogging y contenido dinámico en exteriores.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2024/10/Disenosintitulo-2024-09-18T165348.312-1000x1000.webp",
        "categoryId": 3,
        "stock": 10
    },

{
        "name": "DJI Mic Mini Dual",
        "price": 799900,
        "description": "El DJI Mic Mini Dual es el sistema perfecto para creadores que necesitan audio claro y profesional en un formato compacto. Con dos transmisores ultraligeros, captación nítida y conexión estable, es ideal para entrevistas, vlogs y grabaciones en movimiento. El combo incluye dos micrófonos, receptor, estuche de carga, adaptadores y accesorios esenciales para mejorar cualquier producción. Diseñado para ofrecer sonido limpio, fiable y fácil de usar en todo tipo de proyectos.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2024/11/DJI-Mic-Mini-%EF%BC%88%E4%B8%A4%E5%8F%91%E4%B8%80%E6%94%B6%EF%BC%8C%E5%90%AB%E5%85%85%E7%94%B5%E7%9B%92%EF%BC%89%E2%80%94%E5%B7%A6%E4%BE%A745%E5%BA%A6-DJI-Mic-Mini-%EF%BC%882TX1RXCharging-Case%EF%BC%89%E2%80%94Left-Side-45-Degree-1-scaled.jpg",
        "categoryId": 2,
        "stock": 10
    },

{
        "name": "Adaptador teléfono DJI Mic Mini (Lightning)",
        "price": 119900,
        "description": "El Adaptador para teléfono DJI Mic Mini (Lightning) permite conectar el sistema de micrófono a dispositivos Apple con puerto Lightning. Ofrece transmisión de audio estable y de baja latencia, ideal para grabar contenido móvil con alta calidad. Su diseño compacto y plug-and-play facilita un uso rápido, práctico y profesional.",
        "image": "https://tiendadefotografia.com.co/wp-content/uploads/2025/03/517cd7aa1cd2b1b29462c99cbb4a7d34@origin-scaled.jpg",
        "categoryId": 2,
        "stock": 10
    },